sudo: required

language: php

php:
  - "7.1"
  
env:
  - WP_VERSION=latest
  
before_script:
    - export PLUGIN_SLUG=$(basename $(pwd))
    - git clone https://github.com/WordPress/WordPress.git /tmp/wordpress
    - mkdir -p /tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG/tests
    - cp -a src/. /tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG
    - cp -a tests/. /tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG/tests
    - cp -a phpunit.xml /tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cd /tmp/wordpress
    - cp wp-config-sample.php wp-config.php
    - sed -i "s/database_name_here/wordpress_tests/" wp-config.php
    - sed -i "s/username_here/travis/" wp-config.php
    - sed -i "s/password_here//" wp-config.php
    - cd "/tmp/wordpress/wp-content/plugins/$PLUGIN_SLUG"
    - ls
    
script: phpunit --configuration phpunit.xml
