sudo: required

language: php

php:
  - "7.1"
  
env:
  - WP_VERSION=latest
  
before_script:
    - export PLUGIN_SLUG=$(basename $(pwd))
    - git clone git://develop.git.wordpress.org/ /tmp/wordpress
    - rm -rf /tmp/wordpress/tests/phpunit/tests/*
    - cp -a tests/test_* /tmp/wordpress/tests/phpunit/tests/
    - ls /tmp/wordpress/tests/phpunit/tests/
    - mkdir -p /tmp/wordpress/build/wp-content/plugins/$PLUGIN_SLUG/
    - cp -a src/. /tmp/wordpress/build/wp-content/plugins/$PLUGIN_SLUG
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - wget https://github.com/woocommerce/woocommerce/archive/3.4.6.zip
    - unzip 3.4.6.zip -d /tmp/wordpress/build/wp-content/plugins/
    - mv /tmp/wordpress/build/wp-content/plugins/woocommerce-3.4.6 /tmp/wordpress/build/wp-content/plugins/woocommerce
    - cd /tmp/wordpress/
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    - npm install -g grunt-cli
    - npm install
    - grunt build
    
script:
    - phpunit

after_success:
    - test $TRAVIS_BRANCH = "dev" && echo "On dev branch"
