sudo: required

language: php

php:
  - "7.1"
  
env:
  - WP_VERSION=latest
  
before_script:
    - export PLUGIN_SLUG=$(basename $(pwd))
    - git clone https://github.com/WordPress/WordPress.git /tmp/wordpress
    - git clone . "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - cd /tmp/wordpress
    - git checkout $WP_VERSION
    - cd /tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG
    - git checkout dev
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    - cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"

script: phpunit
